# Generated by Django 3.2.20 on 2023-07-22 01:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('availability_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='availability',
        ),
        migrations.AddField(
            model_name='employeeavailability',
            name='employee',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='availability_app.employee'),
            preserve_default=False,
        ),
    ]
